// GeoProvider.js — country registry + pack contract.
//
// 198 countries: Nepal ships districts (ADM2, local source), every other
// country ships first-level boundaries (geoBoundaries, simplified + further
// reduced for the map). UI stays identical: every pack normalizes to
//   { id, name, province, provinceName, rings: [[[lon,lat]]] }
// `unit` is the singular word for one area ("district", "state", ...).
// Attribution: local data only

var REGISTRY = [
  { iso: "NP", iso2: "NP", name: "nepal", file: "nepal-districts.json", unit: "district", groupUnit: "province", total: 77, ready: true },
  { iso: "AFG", iso2: "AF", name: "afghanistan", file: "packs/AFG.json", unit: "province", total: 34, ready: true },
  { iso: "AGO", iso2: "AO", name: "angola", file: "packs/AGO.json", unit: "province", total: 18, ready: true },
  { iso: "ALB", iso2: "AL", name: "albania", file: "packs/ALB.json", unit: "county", total: 12, ready: true },
  { iso: "AND", iso2: "AD", name: "andorra", file: "packs/AND.json", unit: "parish", total: 7, ready: true },
  { iso: "ARE", iso2: "AE", name: "united arab emirates", file: "packs/ARE.json", unit: "emirate", total: 7, ready: true },
  { iso: "ARG", iso2: "AR", name: "argentina", file: "packs/ARG.json", unit: "province", total: 23, ready: true },
  { iso: "ARM", iso2: "AM", name: "armenia", file: "packs/ARM.json", unit: "province", total: 11, ready: true },
  { iso: "ATG", iso2: "AG", name: "antigua", file: "packs/ATG.json", unit: "parish", total: 8, ready: true },
  { iso: "AUS", iso2: "AU", name: "australia", file: "packs/AUS.json", unit: "state", total: 9, ready: true },
  { iso: "AUT", iso2: "AT", name: "austria", file: "packs/AUT.json", unit: "state", total: 9, ready: true },
  { iso: "AZE", iso2: "AZ", name: "azerbaijan", file: "packs/AZE.json", unit: "district", total: 2, ready: true },
  { iso: "BDI", iso2: "BI", name: "burundi", file: "packs/BDI.json", unit: "province", total: 18, ready: true },
  { iso: "BEL", iso2: "BE", name: "belgium", file: "packs/BEL.json", unit: "province", total: 3, ready: true },
  { iso: "BEN", iso2: "BJ", name: "benin", file: "packs/BEN.json", unit: "department", total: 12, ready: true },
  { iso: "BFA", iso2: "BF", name: "burkina faso", file: "packs/BFA.json", unit: "region", total: 13, ready: true },
  { iso: "BGD", iso2: "BD", name: "bangladesh", file: "packs/BGD.json", unit: "division", total: 8, ready: true },
  { iso: "BGR", iso2: "BG", name: "bulgaria", file: "packs/BGR.json", unit: "province", total: 28, ready: true },
  { iso: "BHR", iso2: "BH", name: "bahrain", file: "packs/BHR.json", unit: "governorate", total: 4, ready: true },
  { iso: "BHS", iso2: "BS", name: "bahamas", file: "packs/BHS.json", unit: "district", total: 32, ready: true },
  { iso: "BIH", iso2: "BA", name: "bosnia", file: "packs/BIH.json", unit: "canton", total: 3, ready: true },
  { iso: "BLR", iso2: "BY", name: "belarus", file: "packs/BLR.json", unit: "region", total: 7, ready: true },
  { iso: "BLZ", iso2: "BZ", name: "belize", file: "packs/BLZ.json", unit: "district", total: 6, ready: true },
  { iso: "BOL", iso2: "BO", name: "bolivia", file: "packs/BOL.json", unit: "department", total: 9, ready: true },
  { iso: "BRA", iso2: "BR", name: "brazil", file: "packs/BRA.json", unit: "state", total: 27, ready: true },
  { iso: "BRB", iso2: "BB", name: "barbados", file: "packs/BRB.json", unit: "parish", total: 11, ready: true },
  { iso: "BRN", iso2: "BN", name: "brunei", file: "packs/BRN.json", unit: "district", total: 4, ready: true },
  { iso: "BTN", iso2: "BT", name: "bhutan", file: "packs/BTN.json", unit: "district", total: 20, ready: true },
  { iso: "BWA", iso2: "BW", name: "botswana", file: "packs/BWA.json", unit: "district", total: 10, ready: true },
  { iso: "CAF", iso2: "CF", name: "central african republic", file: "packs/CAF.json", unit: "prefecture", total: 16, ready: true },
  { iso: "CAN", iso2: "CA", name: "canada", file: "packs/CAN.json", unit: "province", total: 13, ready: true },
  { iso: "CHE", iso2: "CH", name: "switzerland", file: "packs/CHE.json", unit: "canton", total: 26, ready: true },
  { iso: "CHL", iso2: "CL", name: "chile", file: "packs/CHL.json", unit: "region", total: 16, ready: true },
  { iso: "CHN", iso2: "CN", name: "china", file: "packs/CHN.json", unit: "province", total: 34, ready: true },
  { iso: "CIV", iso2: "CI", name: "cote d'ivoire", file: "packs/CIV.json", unit: "district", total: 14, ready: true },
  { iso: "CMR", iso2: "CM", name: "cameroon", file: "packs/CMR.json", unit: "region", total: 10, ready: true },
  { iso: "COD", iso2: "CD", name: "dr congo", file: "packs/COD.json", unit: "province", total: 26, ready: true },
  { iso: "COG", iso2: "CG", name: "congo", file: "packs/COG.json", unit: "department", total: 12, ready: true },
  { iso: "COL", iso2: "CO", name: "colombia", file: "packs/COL.json", unit: "department", total: 33, ready: true },
  { iso: "COM", iso2: "KM", name: "comoros", file: "packs/COM.json", unit: "island", total: 3, ready: true },
  { iso: "CPV", iso2: "CV", name: "cape verde", file: "packs/CPV.json", unit: "municipality", total: 22, ready: true },
  { iso: "CRI", iso2: "CR", name: "costa rica", file: "packs/CRI.json", unit: "province", total: 7, ready: true },
  { iso: "CUB", iso2: "CU", name: "cuba", file: "packs/CUB.json", unit: "province", total: 16, ready: true },
  { iso: "CYP", iso2: "CY", name: "cyprus", file: "packs/CYP.json", unit: "district", total: 6, ready: true },
  { iso: "CZE", iso2: "CZ", name: "czechia", file: "packs/CZE.json", unit: "region", total: 14, ready: true },
  { iso: "DEU", iso2: "DE", name: "germany", file: "packs/DEU.json", unit: "state", total: 16, ready: true },
  { iso: "DJI", iso2: "DJ", name: "djibouti", file: "packs/DJI.json", unit: "region", total: 6, ready: true },
  { iso: "DMA", iso2: "DM", name: "dominica", file: "packs/DMA.json", unit: "parish", total: 10, ready: true },
  { iso: "DNK", iso2: "DK", name: "denmark", file: "packs/DNK.json", unit: "region", total: 5, ready: true },
  { iso: "DOM", iso2: "DO", name: "dominican republic", file: "packs/DOM.json", unit: "province", total: 32, ready: true },
  { iso: "DZA", iso2: "DZ", name: "algeria", file: "packs/DZA.json", unit: "province", total: 48, ready: true },
  { iso: "ECU", iso2: "EC", name: "ecuador", file: "packs/ECU.json", unit: "province", total: 23, ready: true },
  { iso: "EGY", iso2: "EG", name: "egypt", file: "packs/EGY.json", unit: "governorate", total: 27, ready: true },
  { iso: "ERI", iso2: "ER", name: "eritrea", file: "packs/ERI.json", unit: "region", total: 6, ready: true },
  { iso: "ESP", iso2: "ES", name: "spain", file: "packs/ESP.json", unit: "province", total: 19, ready: true },
  { iso: "EST", iso2: "EE", name: "estonia", file: "packs/EST.json", unit: "county", total: 15, ready: true },
  { iso: "ETH", iso2: "ET", name: "ethiopia", file: "packs/ETH.json", unit: "region", total: 11, ready: true },
  { iso: "FIN", iso2: "FI", name: "finland", file: "packs/FIN.json", unit: "region", total: 19, ready: true },
  { iso: "FJI", iso2: "FJ", name: "fiji", file: "packs/FJI.json", unit: "division", total: 4, ready: true },
  { iso: "FRA", iso2: "FR", name: "france", file: "packs/FRA.json", unit: "region", total: 13, ready: true },
  { iso: "FSM", iso2: "FM", name: "micronesia", file: "packs/FSM.json", unit: "state", total: 4, ready: true },
  { iso: "GAB", iso2: "GA", name: "gabon", file: "packs/GAB.json", unit: "province", total: 9, ready: true },
  { iso: "GBR", iso2: "GB", name: "united kingdom", file: "packs/GBR.json", unit: "country", total: 4, ready: true },
  { iso: "GEO", iso2: "GE", name: "georgia", file: "packs/GEO.json", unit: "region", total: 12, ready: true },
  { iso: "GHA", iso2: "GH", name: "ghana", file: "packs/GHA.json", unit: "region", total: 16, ready: true },
  { iso: "GIN", iso2: "GN", name: "guinea", file: "packs/GIN.json", unit: "region", total: 8, ready: true },
  { iso: "GMB", iso2: "GM", name: "gambia", file: "packs/GMB.json", unit: "division", total: 6, ready: true },
  { iso: "GNB", iso2: "GW", name: "guinea-bissau", file: "packs/GNB.json", unit: "region", total: 9, ready: true },
  { iso: "GNQ", iso2: "GQ", name: "equatorial guinea", file: "packs/GNQ.json", unit: "province", total: 7, ready: true },
  { iso: "GRC", iso2: "GR", name: "greece", file: "packs/GRC.json", unit: "region", total: 8, ready: true },
  { iso: "GRD", iso2: "GD", name: "grenada", file: "packs/GRD.json", unit: "parish", total: 7, ready: true },
  { iso: "GRL", iso2: "GL", name: "greenland", file: "packs/GRL.json", unit: "municipality", total: 6, ready: true },
  { iso: "GTM", iso2: "GT", name: "guatemala", file: "packs/GTM.json", unit: "department", total: 22, ready: true },
  { iso: "GUY", iso2: "GY", name: "guyana", file: "packs/GUY.json", unit: "region", total: 10, ready: true },
  { iso: "HND", iso2: "HN", name: "honduras", file: "packs/HND.json", unit: "department", total: 18, ready: true },
  { iso: "HRV", iso2: "HR", name: "croatia", file: "packs/HRV.json", unit: "county", total: 21, ready: true },
  { iso: "HTI", iso2: "HT", name: "haiti", file: "packs/HTI.json", unit: "department", total: 10, ready: true },
  { iso: "HUN", iso2: "HU", name: "hungary", file: "packs/HUN.json", unit: "county", total: 19, ready: true },
  { iso: "IDN", iso2: "ID", name: "indonesia", file: "packs/IDN.json", unit: "province", total: 34, ready: true },
  { iso: "IND", iso2: "IN", name: "india", file: "packs/IND.json", unit: "state", total: 36, ready: true },
  { iso: "IRL", iso2: "IE", name: "ireland", file: "packs/IRL.json", unit: "county", total: 4, ready: true },
  { iso: "IRN", iso2: "IR", name: "iran", file: "packs/IRN.json", unit: "province", total: 31, ready: true },
  { iso: "IRQ", iso2: "IQ", name: "iraq", file: "packs/IRQ.json", unit: "governorate", total: 18, ready: true },
  { iso: "ISL", iso2: "IS", name: "iceland", file: "packs/ISL.json", unit: "region", total: 8, ready: true },
  { iso: "ISR", iso2: "IL", name: "israel", file: "packs/ISR.json", unit: "district", total: 6, ready: true },
  { iso: "ITA", iso2: "IT", name: "italy", file: "packs/ITA.json", unit: "province", total: 5, ready: true },
  { iso: "JAM", iso2: "JM", name: "jamaica", file: "packs/JAM.json", unit: "parish", total: 14, ready: true },
  { iso: "JOR", iso2: "JO", name: "jordan", file: "packs/JOR.json", unit: "governorate", total: 12, ready: true },
  { iso: "JPN", iso2: "JP", name: "japan", file: "packs/JPN.json", unit: "prefecture", total: 47, ready: true },
  { iso: "KAZ", iso2: "KZ", name: "kazakhstan", file: "packs/KAZ.json", unit: "region", total: 16, ready: true },
  { iso: "KEN", iso2: "KE", name: "kenya", file: "packs/KEN.json", unit: "county", total: 47, ready: true },
  { iso: "KGZ", iso2: "KG", name: "kyrgyzstan", file: "packs/KGZ.json", unit: "region", total: 7, ready: true },
  { iso: "KHM", iso2: "KH", name: "cambodia", file: "packs/KHM.json", unit: "province", total: 25, ready: true },
  { iso: "KIR", iso2: "KI", name: "kiribati", file: "packs/KIR.json", unit: "region", total: 3, ready: true },
  { iso: "KNA", iso2: "KN", name: "st kitts", file: "packs/KNA.json", unit: "parish", total: 14, ready: true },
  { iso: "KOR", iso2: "KR", name: "south korea", file: "packs/KOR.json", unit: "province", total: 17, ready: true },
  { iso: "KWT", iso2: "KW", name: "kuwait", file: "packs/KWT.json", unit: "governorate", total: 6, ready: true },
  { iso: "LAO", iso2: "LA", name: "laos", file: "packs/LAO.json", unit: "province", total: 18, ready: true },
  { iso: "LBN", iso2: "LB", name: "lebanon", file: "packs/LBN.json", unit: "governorate", total: 9, ready: true },
  { iso: "LBR", iso2: "LR", name: "liberia", file: "packs/LBR.json", unit: "county", total: 15, ready: true },
  { iso: "LBY", iso2: "LY", name: "libya", file: "packs/LBY.json", unit: "district", total: 22, ready: true },
  { iso: "LCA", iso2: "LC", name: "st lucia", file: "packs/LCA.json", unit: "parish", total: 10, ready: true },
  { iso: "LIE", iso2: "LI", name: "liechtenstein", file: "packs/LIE.json", unit: "municipality", total: 11, ready: true },
  { iso: "LKA", iso2: "LK", name: "sri lanka", file: "packs/LKA.json", unit: "district", total: 9, ready: true },
  { iso: "LSO", iso2: "LS", name: "lesotho", file: "packs/LSO.json", unit: "district", total: 10, ready: true },
  { iso: "LTU", iso2: "LT", name: "lithuania", file: "packs/LTU.json", unit: "municipality", total: 10, ready: true },
  { iso: "LUX", iso2: "LU", name: "luxembourg", file: "packs/LUX.json", unit: "canton", total: 12, ready: true },
  { iso: "LVA", iso2: "LV", name: "latvia", file: "packs/LVA.json", unit: "municipality", total: 42, ready: true },
  { iso: "MAR", iso2: "MA", name: "morocco", file: "packs/MAR.json", unit: "region", total: 12, ready: true },
  { iso: "MCO", iso2: "MC", name: "monaco", file: "packs/MCO.json", unit: "ward", total: 1, ready: true },
  { iso: "MDA", iso2: "MD", name: "moldova", file: "packs/MDA.json", unit: "district", total: 37, ready: true },
  { iso: "MDG", iso2: "MG", name: "madagascar", file: "packs/MDG.json", unit: "region", total: 22, ready: true },
  { iso: "MDV", iso2: "MV", name: "maldives", file: "packs/MDV.json", unit: "atoll", total: 21, ready: true },
  { iso: "MEX", iso2: "MX", name: "mexico", file: "packs/MEX.json", unit: "state", total: 31, ready: true },
  { iso: "MHL", iso2: "MH", name: "marshall islands", file: "packs/MHL.json", unit: "region", total: 24, ready: true },
  { iso: "MKD", iso2: "MK", name: "north macedonia", file: "packs/MKD.json", unit: "municipality", total: 8, ready: true },
  { iso: "MLI", iso2: "ML", name: "mali", file: "packs/MLI.json", unit: "region", total: 9, ready: true },
  { iso: "MLT", iso2: "MT", name: "malta", file: "packs/MLT.json", unit: "region", total: 67, ready: true },
  { iso: "MMR", iso2: "MM", name: "myanmar", file: "packs/MMR.json", unit: "region", total: 14, ready: true },
  { iso: "MNE", iso2: "ME", name: "montenegro", file: "packs/MNE.json", unit: "region", total: 23, ready: true },
  { iso: "MNG", iso2: "MN", name: "mongolia", file: "packs/MNG.json", unit: "province", total: 22, ready: true },
  { iso: "MOZ", iso2: "MZ", name: "mozambique", file: "packs/MOZ.json", unit: "province", total: 10, ready: true },
  { iso: "MRT", iso2: "MR", name: "mauritania", file: "packs/MRT.json", unit: "region", total: 13, ready: true },
  { iso: "MUS", iso2: "MU", name: "mauritius", file: "packs/MUS.json", unit: "district", total: 12, ready: true },
  { iso: "MWI", iso2: "MW", name: "malawi", file: "packs/MWI.json", unit: "district", total: 3, ready: true },
  { iso: "MYS", iso2: "MY", name: "malaysia", file: "packs/MYS.json", unit: "state", total: 16, ready: true },
  { iso: "NAM", iso2: "NA", name: "namibia", file: "packs/NAM.json", unit: "region", total: 13, ready: true },
  { iso: "NER", iso2: "NE", name: "niger", file: "packs/NER.json", unit: "region", total: 6, ready: true },
  { iso: "NGA", iso2: "NG", name: "nigeria", file: "packs/NGA.json", unit: "state", total: 37, ready: true },
  { iso: "NIC", iso2: "NI", name: "nicaragua", file: "packs/NIC.json", unit: "department", total: 17, ready: true },
  { iso: "NIU", iso2: "NU", name: "niue", file: "packs/NIU.json", unit: "village", total: 14, ready: true },
  { iso: "NLD", iso2: "NL", name: "netherlands", file: "packs/NLD.json", unit: "province", total: 12, ready: true },
  { iso: "NOR", iso2: "NO", name: "norway", file: "packs/NOR.json", unit: "county", total: 11, ready: true },
  { iso: "NRU", iso2: "NR", name: "nauru", file: "packs/NRU.json", unit: "district", total: 14, ready: true },
  { iso: "NZL", iso2: "NZ", name: "new zealand", file: "packs/NZL.json", unit: "region", total: 17, ready: true },
  { iso: "OMN", iso2: "OM", name: "oman", file: "packs/OMN.json", unit: "governorate", total: 7, ready: true },
  { iso: "PAK", iso2: "PK", name: "pakistan", file: "packs/PAK.json", unit: "province", total: 7, ready: true },
  { iso: "PAN", iso2: "PA", name: "panama", file: "packs/PAN.json", unit: "province", total: 13, ready: true },
  { iso: "PER", iso2: "PE", name: "peru", file: "packs/PER.json", unit: "region", total: 26, ready: true },
  { iso: "PHL", iso2: "PH", name: "philippines", file: "packs/PHL.json", unit: "province", total: 17, ready: true },
  { iso: "PLW", iso2: "PW", name: "palau", file: "packs/PLW.json", unit: "region", total: 16, ready: true },
  { iso: "PNG", iso2: "PG", name: "papua new guinea", file: "packs/PNG.json", unit: "province", total: 22, ready: true },
  { iso: "POL", iso2: "PL", name: "poland", file: "packs/POL.json", unit: "voivodeship", total: 16, ready: true },
  { iso: "PRK", iso2: "KP", name: "north korea", file: "packs/PRK.json", unit: "province", total: 11, ready: true },
  { iso: "PRT", iso2: "PT", name: "portugal", file: "packs/PRT.json", unit: "district", total: 20, ready: true },
  { iso: "PRY", iso2: "PY", name: "paraguay", file: "packs/PRY.json", unit: "department", total: 18, ready: true },
  { iso: "PSE", iso2: "PS", name: "palestine", file: "packs/PSE.json", unit: "governorate", total: 2, ready: true },
  { iso: "QAT", iso2: "QA", name: "qatar", file: "packs/QAT.json", unit: "municipality", total: 8, ready: true },
  { iso: "ROU", iso2: "RO", name: "romania", file: "packs/ROU.json", unit: "county", total: 42, ready: true },
  { iso: "RUS", iso2: "RU", name: "russia", file: "packs/RUS.json", unit: "region", total: 83, ready: true },
  { iso: "RWA", iso2: "RW", name: "rwanda", file: "packs/RWA.json", unit: "district", total: 5, ready: true },
  { iso: "SAU", iso2: "SA", name: "saudi arabia", file: "packs/SAU.json", unit: "province", total: 13, ready: true },
  { iso: "SDN", iso2: "SD", name: "sudan", file: "packs/SDN.json", unit: "state", total: 19, ready: true },
  { iso: "SEN", iso2: "SN", name: "senegal", file: "packs/SEN.json", unit: "region", total: 14, ready: true },
  { iso: "SGP", iso2: "SG", name: "singapore", file: "packs/SGP.json", unit: "region", total: 5, ready: true },
  { iso: "SLB", iso2: "SB", name: "solomon islands", file: "packs/SLB.json", unit: "province", total: 10, ready: true },
  { iso: "SLE", iso2: "SL", name: "sierra leone", file: "packs/SLE.json", unit: "district", total: 4, ready: true },
  { iso: "SLV", iso2: "SV", name: "el salvador", file: "packs/SLV.json", unit: "department", total: 14, ready: true },
  { iso: "SMR", iso2: "SM", name: "san marino", file: "packs/SMR.json", unit: "municipality", total: 9, ready: true },
  { iso: "SOM", iso2: "SO", name: "somalia", file: "packs/SOM.json", unit: "region", total: 18, ready: true },
  { iso: "SRB", iso2: "RS", name: "serbia", file: "packs/SRB.json", unit: "district", total: 25, ready: true },
  { iso: "SSD", iso2: "SS", name: "south sudan", file: "packs/SSD.json", unit: "state", total: 10, ready: true },
  { iso: "STP", iso2: "ST", name: "sao tome", file: "packs/STP.json", unit: "region", total: 2, ready: true },
  { iso: "SUR", iso2: "SR", name: "suriname", file: "packs/SUR.json", unit: "district", total: 10, ready: true },
  { iso: "SVK", iso2: "SK", name: "slovakia", file: "packs/SVK.json", unit: "region", total: 8, ready: true },
  { iso: "SVN", iso2: "SI", name: "slovenia", file: "packs/SVN.json", unit: "macroregions", total: 2, ready: true },
  { iso: "SWE", iso2: "SE", name: "sweden", file: "packs/SWE.json", unit: "county", total: 21, ready: true },
  { iso: "SWZ", iso2: "SZ", name: "eswatini", file: "packs/SWZ.json", unit: "region", total: 4, ready: true },
  { iso: "SYC", iso2: "SC", name: "seychelles", file: "packs/SYC.json", unit: "region", total: 26, ready: true },
  { iso: "SYR", iso2: "SY", name: "syria", file: "packs/SYR.json", unit: "governorate", total: 14, ready: true },
  { iso: "TCD", iso2: "TD", name: "chad", file: "packs/TCD.json", unit: "region", total: 23, ready: true },
  { iso: "TGO", iso2: "TG", name: "togo", file: "packs/TGO.json", unit: "region", total: 5, ready: true },
  { iso: "THA", iso2: "TH", name: "thailand", file: "packs/THA.json", unit: "province", total: 77, ready: true },
  { iso: "TJK", iso2: "TJ", name: "tajikistan", file: "packs/TJK.json", unit: "region", total: 5, ready: true },
  { iso: "TKM", iso2: "TM", name: "turkmenistan", file: "packs/TKM.json", unit: "region", total: 5, ready: true },
  { iso: "TLS", iso2: "TL", name: "timor-leste", file: "packs/TLS.json", unit: "municipality", total: 13, ready: true },
  { iso: "TON", iso2: "TO", name: "tonga", file: "packs/TON.json", unit: "region", total: 5, ready: true },
  { iso: "TTO", iso2: "TT", name: "trinidad", file: "packs/TTO.json", unit: "region", total: 14, ready: true },
  { iso: "TUN", iso2: "TN", name: "tunisia", file: "packs/TUN.json", unit: "governorate", total: 24, ready: true },
  { iso: "TUR", iso2: "TR", name: "turkey", file: "packs/TUR.json", unit: "province", total: 81, ready: true },
  { iso: "TUV", iso2: "TV", name: "tuvalu", file: "packs/TUV.json", unit: "region", total: 8, ready: true },
  { iso: "TWN", iso2: "TW", name: "taiwan", file: "packs/TWN.json", unit: "county", total: 22, ready: true },
  { iso: "TZA", iso2: "TZ", name: "tanzania", file: "packs/TZA.json", unit: "region", total: 30, ready: true },
  { iso: "UGA", iso2: "UG", name: "uganda", file: "packs/UGA.json", unit: "district", total: 4, ready: true },
  { iso: "UKR", iso2: "UA", name: "ukraine", file: "packs/UKR.json", unit: "oblast", total: 27, ready: true },
  { iso: "URY", iso2: "UY", name: "uruguay", file: "packs/URY.json", unit: "department", total: 19, ready: true },
  { iso: "USA", iso2: "US", name: "united states", file: "packs/USA.json", unit: "state", total: 56, ready: true },
  { iso: "UZB", iso2: "UZ", name: "uzbekistan", file: "packs/UZB.json", unit: "region", total: 14, ready: true },
  { iso: "VCT", iso2: "VC", name: "st vincent", file: "packs/VCT.json", unit: "parish", total: 6, ready: true },
  { iso: "VEN", iso2: "VE", name: "venezuela", file: "packs/VEN.json", unit: "state", total: 25, ready: true },
  { iso: "VNM", iso2: "VN", name: "viet nam", file: "packs/VNM.json", unit: "province", total: 63, ready: true },
  { iso: "VUT", iso2: "VU", name: "vanuatu", file: "packs/VUT.json", unit: "province", total: 6, ready: true },
  { iso: "WSM", iso2: "WS", name: "samoa", file: "packs/WSM.json", unit: "region", total: 11, ready: true },
  { iso: "XKX", iso2: "", name: "kosovo", file: "packs/XKX.json", unit: "municipality", total: 7, ready: true },
  { iso: "YEM", iso2: "YE", name: "yemen", file: "packs/YEM.json", unit: "governorate", total: 22, ready: true },
  { iso: "ZAF", iso2: "ZA", name: "south africa", file: "packs/ZAF.json", unit: "province", total: 9, ready: true },
  { iso: "ZMB", iso2: "ZM", name: "zambia", file: "packs/ZMB.json", unit: "province", total: 10, ready: true },
  { iso: "ZWE", iso2: "ZW", name: "zimbabwe", file: "packs/ZWE.json", unit: "province", total: 10, ready: true },
]

// The 20 most populous countries: front-row in setup, premium geometry.
// NOTE: kept by hand — registry rebuilds must preserve this block.
var FEATURED = ["CHN", "IND", "USA", "IDN", "PAK", "NGA", "BRA", "BGD",
  "RUS", "MEX", "ETH", "JPN", "PHL", "EGY", "COD", "VNM", "IRN", "TUR",
  "DEU", "THA"]

function entryFor(iso) {
  for (var i = 0; i < REGISTRY.length; i++)
    if (REGISTRY[i].iso === iso) return REGISTRY[i]
  return null
}

function entryForIso2(iso2) {
  iso2 = String(iso2 || "").toUpperCase()
  if (iso2 === "NP") return entryFor("NP")
  for (var i = 0; i < REGISTRY.length; i++)
    if (REGISTRY[i].iso2 === iso2) return REGISTRY[i]
  return null
}

// NOTE: packs load through components/GeoPack.qml (FileView), not
// XHR — QML XMLHttpRequest refuses file:// reads.
